# -*- coding: utf-8 -*-
"""Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c28WMCG3my8fEZKDaaL7bV6hWM4hekx6
"""

import sys, os

sys.path.append(os.path.join(os.path.dirname(__file__)))

import Class_Unit as unit

unit.GameObj()

import Class_Battle as battle

battle.GameObj()

